### ISSUE TITLE
I have a lag every few seconds what I had in FTB Beyond

### ISSUE THREAD

**Issue by Frytas53** [waggz81/smashphyro-modpack#3]
In one version of _**FTB Beyond**_ started lag every few seconds. I see it in this modpack too. I' m thinking it' s _**one of the mods**_, but I don' t know which. I have that lags **only at this 2 modpacks.**

**Comment by waggz81** [comment]
Can you try adding the following parameters and see if it helps? I added these to my Twitch Settings > Minecraft > Advanced > Additional Java Parameters after noticing an issue with garbage collection using very high res texture packs and I have no issues now.

`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by waggz81** [comment]
@Frytas53 please try this and let me know how it goes. Also please hit F3 and check the memory usage in top right corner and see if the pauses line up with memory being reduced.

**Comment by Frytas53** [comment]
**Doesn't helped.** Memory gets to 97% and Lag [https://www.youtube.com/watch?v=qGbJQEGLqKw&feature=youtu.be](url)

**Comment by Frytas53** [comment]
Memory up to 8GB
