### ISSUE TITLE
Twitch Description - Help Wanted!

### ISSUE THREAD

**Issue by waggz81** [waggz81/smashphyro-modpack#5]
Please assist with suggestion on how to describe the mod pack so it may be approved on Twitch launcher!

**Twitch has rejected mod pack description with the following:**

> Your project requires a better description. You can change this by clicking Settings above the description on the project page. 
> The project description must contain these facts: 
> - Features offered by the project. 
> - How those features affect a user's experience. 
> Be as thorough as possible, and avoid vague statements. Potential users should have a reason to consider using what you are offering. 
> Things which are not considered to be a valid description: 
> - Links to demonstration videos. 
> - Links to descriptions of your project on another site. 
> - Names of or links to other projects. These provide no explanation of what your project does, without prior knowledge of those projects. 
> - A short story. 
> - A question-and-answer session. 
> - An advertisement. 
> - A biography: "My name is X and this is my first project!"

**This is the most recent submission by porphyro:**
> Smashphyro is a modpack created for your favorite monkey Smashkeys and your favorite polar bear Porphyro. It contains their favorite mods into one pack with classics like Botania, Thermal Expansion and new mods they can't wait to test like AbyssalCraft, EvilCraft, and Astral Sorcery. This modpack combines Smashkeys' need for tech, automation, and science with Porphyro's love of farming, magic, and building.
> 
> Also there's plants everywhere.

**Comment by DeuxVis** [comment]
As far as I understand it could be the fact that "Names of other projects" - IE mods names - were used which made it rejected.

The description should be self-contained - IE not need to lookup elsewhere what a certain mods does, etc

Instead we should describe what can be done with the modpack : explore space, gather rare plants, ...
I'm sorry not to be able to write it myself but I don't know what are the main "things to do" that should be listed - not knowing most of the mods there.

**Comment by waggz81** [comment]
Mod Pack now on Twitch! Thank you for your help everyone!!
